version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.SpaServices.Extensions
    versions:
    - 5.0.2
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.2
